### PR TITLE
Slightly better fix for default export

### PR DESCRIPTION
**Pull request by andrew-w-ross**
Changes package.json to module
Updates tsup to export both commonjs and esm

### CODE REVIEW

**Comment by danielwaltz** [comment]
@andrew-w-ross This looks excellent, nice investigation and very nice solution. I think all I'd ask is that the commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) format with a `fix:` prefix so semantic release bot can release it properly, and I'll go ahead and merge it!

**Comment by andrew-w-ross** [comment]
@danialwaltz Thanks, Let me know if I got the commit message correct before I update my other pr. Might be worth adding a precommit hook.

**Comment by danielwaltz** [comment]
@andrew-w-ross Looks good! I think it should work like that, technically the spec says to keep it all lowercase `fix:` but it may still work titlecase `Fix:` too. 🤔 I'm honestly not sure though. It might need to be changed to lower case just in case!

If you're using VSCode, I've started using this extension to help walk me through creating commits in this format and it's been very nice! https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits

**Comment by andrew-w-ross** [comment]
@danielwaltz Looks like there is a [commitlint hook](https://github.com/conventional-changelog/commitlint) you can use so regardless they have to get it right. Hopefully I got the commit message right this time.

**Comment by danielwaltz** [comment]
@andrew-w-ross Commit message looks good! Wouldn't hurt to get husky on here and get things more formalized. This is my first open source project with contributions so it's pretty new (and pretty exciting).

Looks like with a package type of `module` eslint isn't happy with a plain `.js` ext for the eslint config. According to the output there, renaming the config file from `.eslintrc.js` to `.eslintrc.cjs` should fix that up too.

A few hoops here, but it's close!

**Comment by andrew-w-ross** [comment]
@danielwaltz Already fixed the rename. I think all you need to add is contributing doc and an issue template and you should be good. Regardless this is an excellent idea for a plugin.

**Review by danielwaltz — APPROVED** [review]

**Comment by danielwaltz** [comment]
@andrew-w-ross Appreciate the feedback and the contributions!

Running into some branch protection issues related to the release now, but once that's buttoned up I'll get these changes out there.

**Comment by andrew-w-ross** [comment]
@danielwaltz Don't know why this didn't show up in my testing but I think it might be best to revert this pr. Until https://github.com/kamilkisiela/graphql-config/issues/1113 is fixed importing as an esmodule will break. Sorry about that.

**Comment by danielwaltz** [comment]
Shoot, is that also the case with the latest version? I had to button up a few things to get it working in my own projects.

**Comment by andrew-w-ross** [comment]
Yeah you'll get the following error on 2.2:

```
error when starting dev server:
TypeError: loadTs is not a function
```

I'll make a pr quick with the fix

**Pull request merged**
